server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /   #应用的上下文路径，详细参考 云枢帮助中心-开发者手册-解决跨域安全问题

spring:
  #redis
  redis:
    host: 127.0.0.1  #地址
    database: 1         #
    password: H3yuncom  #密码
    port: 6379          #端口

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB         #上传单个文件大小限制
      max-request-size: 200MB      #多个同时上传总大小限制

logging:
  level:
    com.authine.cloudpivot: debug   # 云枢产品日志输出级别

dubbo:
  registry:
    protocol: zookeeper
    address: 127.0.0.1  #服务注册地址
    port: 2181          #端口
    timeout: 3000       #超时时间
    check: true
  consumer:
    check: false
    retries: 0          #重试次数

cloudpivot:
  login:
    dingtalk: false #钉钉方式登录
    accountpassword: false #账号密码登录
    dingtalk&accountpassword: true #钉钉扫码和账号密码方式登录
  switch:
    multi_language_toggle_switch: false  #多语言开关 默认关
  attachment:
    oss:
      enabled: false     #是否启用
      accesskeyid:      #用户AccessKey
      accesskeysecret:  #Access Key Secret
      endpoint:         #地域节点 如：oss-cn-shenzhen.aliyuncs.com
      bucket:           #Bucket域名 如：xxx.oss-cn-shenzhen.aliyuncs.com, 其中xxx表示OSS Bucket 名称
      expirtime: 600000 #默认十分钟
    sftp:
      enabled: true     #是否启用
      ftpserver:    #IP 如：120.66.88.11
      ftpport: 22   #端口 如：22
      ftpaccount:   #账号 如：root
      ftppassword:  #密码 如：123456
      ftppath:      #ftp存放地址 如./ftp  .表示当前路径，不配置表示默认当前路径
  api:
    oauth:
      enabled: true   # 是否开启权限校验
      test:
        userid: f8cf3b3469a36a300169a36e88f101eb      # 模拟测试用户ID，不能用于生产环境
  bizlog:
    endpoint:        #地域节点 如：oss-cn-shenzhen.aliyuncs.com
    accessKeyId:     #用户AccessKey
    accessKeySecret: #Access Key Secret
    project:     #SLS项目名称
    logStore: webapi_log    #web-sso日志库
# 自定义静态常量
customize:
  sso:
    # 获取授权码url
    oauthUrl: http://127.0.0.1:8080/api/sso/login?redirect_uri=http://127.0.0.1:8080/api/oauth/authorize?client_id=api&response_type=code&scope=read&redirect_uri=http://127.0.0.1/oauth
    # 对接电话系统使用接口使用加密验证
    publicKey: 30819F300D06092A864886F70D010101050003818D0030818902818100A0B417DA8977B98D00732E96F854FB2D1174E93D9D159BD0612FB9841191C8CD8F1DAF441A0BB34EAE039252501709199C065D1D60D934A1D6BDD4AABA5B988900914128C10C48A2099CA0009678C8EA858B3CD74441A6AFB4F55CF61E24F60714832B2F3F84385AA63E3C44A7CB6141E4ED4A7727A1255634E09F70405DC6F50203010001
    # 需要跳转的页面地址
    systemUrl: http://127.0.0.1
    homeUrl: /workflow-center/my-unfinished-workitem?t=1